---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  radon:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - src/**
  - "**.css"
  - "**.inc"
  - "**.js"
exclude_paths:
- "build/"
- "dist/"
