sudo: required
language: node_js
node_js: 4.5.0
cache:
  timeout: 600
  directories:
  - node_modules
  - jspm_packages
env:
  global:
  - secure: M3U6JYQhZeLHwu6JPjwGJvhre+2eDwrgniY0RfXFHAeIQXtaFXP226odkw6GOreYYxxmfDY3Fo7xljmdSZIGhqJ0ETr2jOh7/lz0tbQxrAeJBDJcwCQa9XdUuuEciiHlPD/ysfeDltq3Mo1elXFDDVDQmX8kxHZuCqwFKoYrZ/lhXI7JRk9EigcomDunnAmNFFcOycBFPnOmYHXLPpOsye6ilnGr6SNvT5O8l84pegHudytDpd7VRvcYr5677YmJbmPbK133yPYJY4kt95z51/EDiGh3J5zSB+7plcti3vGuVKTv8IgC+oAdNKoa25nV3NI6Ye+Kyu3ubSaTW2GLuO06x0uNeEcGmHK5DvtigBPM4DfKh5aC5VjWdNAXhRAE1L6+bmap7kBQqQH07Y04WpKg8eIh62XoyVhKEurXXhUW6j+cPVYYX4FXiGllnTcfUW1pcxgFrkjHwT2VX92hkL8vfC1fU2kfXg5CVaRMY0NMFh3/fAJKtgSPMcdEHYOVZfLz0u2/Yxc95p82cPHnrHbZq3W5TsTPDl3Lfh6wM0osfIkrj87bDaELjt+bIvzNqw1XKgePEW6+POO2GbCxS+B6exFtm4Xri4x7duK8OKJLyDhbRjSYIU/J4BHApaeVPrkjVYtRql173tUV0uTxUiyuiBSdYRssPmYIoQtRxsA=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BRANCH=$TRAVIS_BRANCH
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$HEIMDALL_BRANCH
  - HEIMDALL_PACKAGE_NAME=heimdall-ui-prod-$HEIMDALL_BUILD_LABEL.zip
install:
  - npm install -g gulp
  - npm install -g jspm
  - npm install -g coveralls
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install -y
script:
  - sed -i "s@{BUILD_LABEL}@$HEIMDALL_BUILD_LABEL@" stageConf.js
  - sed -i "s@{BRANCH}@$HEIMDALL_BRANCH@" src/main.js
  - gulp lint
  - gulp bundle
  - npm prune --production
before_deploy:
  - zip -rq $HEIMDALL_PACKAGE_NAME *
  - mkdir -p dpl_cd_upload
  - mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: POUFWbooXUT0sxej9NVu/89O+WqUCVwCuQumB+3vH5eU4qMa3DQy4tFUPw7R19/wzAxDwm+62Jhge+xvlZbKj/tb3coLYXfeTELv8KnWsNZYkavTfU3QbWYzGJv1TMiboNKXOXEExvqNTJPG6uoSS1MvhKchTQKwBge7cdA4MJC3rxjNdVsAyug+UHbLtJqlCpfbkONWWSzzceGh5GuPl8NrbuevScJUBZ/IPGu0uDHbOBeFI/zyk6g14gvF6Ftyww7BNTDCtrebeURljD+oBxjbM3Tfaj7raUYtRYP5vNC+P6SHHjZznJ1h0+FeGSfgfQLBCfpVCfSea7/sSw4xuxmgXKO4N2oDBvbHZqq2AwlvRsZqpq2R3X91YIRvaHDb6BkGgJeKCmNzkyrjruI/qYh5PmoNohhkkv4ilv27Vzney4m87fylRPOWl8c0W1lIE3FoocRABzCh7X9eXOzCoBVtF2IIhj3VKjtxo5MchgDxSxBLrxn2OsRiI93QN+8mbTpGwqtzQpj5yclG57Tu2JiMBDKr3V5+Hdr1i0N3sz8cLJHLR49rvWBEbLrHnsTunGiyVSYWASmoEX+F2FutBBTFuBzyKHlliC4q8CKJwUNfyeBL8lnUY+4oTOJcz2XFO0P96N5m+372pWVC9qgvD8h8e/Ow+0yKjtAMhUt7roA=
  secret_access_key: &2
    secure: MhWw0YgMOoscnZRkx2nuRNeETumNjdj1cxiBiWTpwLbuA8+SBSBRrym/gNsxnWdiJcfnTZV/MHQD/DQjzmfz/vRQ57diEsBfdwJ5qJZw47ajX8SEn+ts0IKBk6OOShziYA3mMGpWbv4elnHe8KEMCFO2Qu3La+E1hCAtMoyslaWds49ix7IRcy12TpU+PRKsSMnSnyROMIXQHobsMPdvJ9JeG7rCR99ziX405sPrXP9o5D44ilOKak+Tqyp/nrmFhXm/uzB3Uap5vqWcvIgetYVlsucBH/O53wcpNy60+NKoFLTVCsdhD7559sfiCt9cbVnujze94H61KLh0S8vmrYxGaP+ei+Rhd0c8sdI60vMQ/bmWgAs12ENKlm4JEXYK7dqZXemRbOYytrG/vR4IVZpoCw5EdeTSCRNPx9rRMKZQpfw/zaQiRKk/75UXQ3GaWbgUsx6VgNq/CnF/vHeYW/3u2j8HRNfLriZJY3q5Ce1tDzC5tf7ihTREOqyzOt6aclT7w3LaTzIUIqBmXCgeDaARHgVBVw3eRlggZb4mPc07fOALMvmPvl+mn0frZddG1D8jswMCfs4HKGWTREvliB8ELOxoD9D7g8Jp0BP2B+Cg0oYRyDPk6NYD1TP5Xvek8onlAsxE86/w7CgfhHjRpTyLLlqZcsmpvQZT0Sroydw"
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-uiapp
    branch: master
  bucket: prod-heimdall-ui-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: prod-heimdall-ui-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: prod-heimdall-ui-app
  deployment_group: prod-heimdall-ui-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
