language: node_js
node_js: 4.4.3
cache:
  directories: node_modules
env:
  global:
  - secure: Ch1QMswEx5wTrgn/TwEFjbMd7p2di9p7NgGTff43EcambfqZeP+NqQQ+RI+fnSXeJWLxrUopSVXZi+CIJEtey4B92lo6J+HetspzVvLygcdenpFzrB4PYiA6YQXj1V/MFzDHZQ75WbgaqWLeuQjR+XteTnWqI8Nd47xbehRELCn4LHsCX82+Ay3s1Ygc0pgwWv526yfmUt4oPj+dPv62KpHkL0tgBm/rcPQgKfJr3P+m5HkL7Mxl4j063KNOe1VksUgZCgdBe9QiVzKrUjPv7zCD2FKHQ/htsjAMATIi8fikL2din8KwAjRCeZ1H1cZMtANeAPyngUQoSrjUi40rUCe49cam2YddYxL00QcelizjR6gR6I9v2J+9jUVHumSbYR8/Z5ol+r3rNOB0IrfMIwdYVgWVRS1LqLMAw0GiUwqin1fi///lmH83LldIPLtT/AODi4Y2virO3+s5JmCJrxK3oQnHRFeEeH9ntUXcQ/YuHpjom2kjDuJifR6XOwPlT2Toap+EMBnagY0lyv/Lap+ENedjXzgVXbgSvINHpGCEyCIY6/2D1yOBnh37cPp7ChMcOtSdZQbqGgRvRlaoZ0xkFmeBSvBQybf5/awh+uaAa2plcXN+y8vAz47lwEjol67ewjNPa5l/cg04pB9WQ94LnNndZSpX1dkdwaJ7KGc=
install:
- npm install -g gulp
- npm install -g jspm
- npm install -g coveralls
- npm install
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install -y
script:
- gulp build
- npm prune --production
before_deploy:
- zip -rq heimdall-uiapp-1.0.0.zip *
- mkdir -p dpl_cd_upload
- mv heimdall-uiapp-1.0.0.zip dpl_cd_upload/heimdall-uiapp-1.0.0.zip
deploy:
- provider: s3
  access_key_id: &1
    secure: KRaLbFj2S733jLaLcyu6zACwFVE1z3S4ADHLFctUto4lg2cVLMh59j84F546z0V4fSf8tYyynX/wMluNDGuTlqb/p/i5ZbaFF0mI+d2RTSqpNNkfGTJgd+C3oet9dFUJMA0kEbBeNH99d69P1nHqIzlVDWZAhZqgIySCAvaT9CIDCRwAe8CywknYIuvGhtLC7tdgIiGy8uWYma5LuGARQZCdftSSy7mZmGWzTEsCWByvIjtEBLzUVO7dFivT002M4BozG8epfXJ8VTYnIy4SkLrNtz3QF6xfsFnve628dmNeq+eY0i41kY2bRyUxTiu73EVf4WhV9YEue/Ftm2QiHJ5qKnbs+G6AuKSmtYvb5Ch5xwjaQdN6AeaW6acTdy9yAaEkCIPk+/3un4idHGoUkzE1zbfC8RC5IsYE5JCZy8t5PdFW1VER4m4knfIi/PXjY4hGRGOL61nzwepP+FQ/WwiKvhOLifGqklj49Ujc+R2KspaN5yrf72riXiXrIePkEohsvIvRuGPgCRZzMkGL/NRFTkG2Ob6Z2gSUgbfEZZmrgPTJLnQpkGhl27jvUsL77n+kAis//9ZTdZ8fXeEb0cRRzv6cLRG3WmY+uHEeH3WQphK7V/WhSvRvZDOO9RDyOPclyNZ6L29dA+z71Jciha1388e+Kuo1/U0C6mjnvL8=
  secret_access_key: &2
    secure: PIEYDBX2Zh6Bh6amt4pJ/HtXFKQ/prQpOSGxKCYpm8sGaNbsdp8HTyX/x+lNUeSt131S+YPZFar/l9v73LbJ30ySvfCv7DV8HkozSjurhsYW0hR+f61JyANq98Od9bi3h3zG+UdDECrO0JnVvL6D5bYCrAEQM//AYrotrjbF6lzWSBvpUjTKCeSWK7qm2ykLyOfVVm5kCSVuaaLSZCF2q4avxPTgQzwAM3lyXtOCvdKA4ynEZQNnBve2cWSw9VT7pEqRXpt45S2e3y2NOa7dscx3WOfpTroZeX6kUXkcHSqC45ZI0uyM6FK+/5j+hXWkhPb9BhPKBiLSHKIRKHGAFrq5HNSHvC24EO+wPFzZ0tE07jyMNqRyL+bSxsfIdy7wbOqysTw7PvG8ialpZVsRisRjk5kelcQ+2GciIkNjlnoUniirhYKtGZyRqDXvpriHd1JYyvQr4BnZEti5XEfp0CmRANdVqQUiHdWBx0MSGF86vQGcBmh863DYEWS8AieB6Gxk9zKnHRMq21N52Q17v8rK+YovZ857Pbss42eyJTL0VNeRhjkXYHOTx/3OLyenoVL3y6nqnRkXmfdT/9fgOO9e23J1yBttxY+ZJ1W6ElBod8wnW3GWXhxDR+rUSR2PvgQseIVZbehoNa51v1Xrg86xP4/S60v/5KfIrxcrcmQ=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-uiapp
    branch: master
  bucket: codedeploy-heimdall-uiapp
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: codedeploy-heimdall-uiapp
  key: heimdall-uiapp-1.0.0.zip
  bundle_type: zip
  application: CodeDeploy-Heimdall-UIApp
  deployment_group: CodeDeploy-HeimdallWebapp-Group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: UQ8y/1HLzbSakJ4YFSZE+yv57VR/Jk2Oab8bKsO36OBM92YKdmYCZqbqesKxKhFOunBmEW2oxXGcN0TmxfCwiR3j6rPTZbsjvyH1xoK1gzrJpk8VmNMIk+LOf3n+1YoScEwFHbalz3df5UNgWd4D02H8WpiVnaNJ7gb+YoxrKYke+vfRc9Q5NKOM8XjEGX4yOfDtKwPIlvDu91jBPA//SFSMZdelVN/gmo2u7MMrE7bJd/hqzG6d53voksqCZ+J+999X6KRxXeTXww0G3rkD13azVEYciTgG96boB/xCu81wHe2gamDLk4cM2IeuBKRPzcern2aB7C2EkycL9raxchs7CGxI7wKTHM4ytOiJFNf6KPy6/BlOJZl9nD85DDTNIdBH9dS48/dmZEO/MYzecSHCquWOPsiTNEIow4sicYI4VJKOj8Zk3Fvi9w3xN2hUztS5Pd0u4AE+gKwNcljj3llkU+H1BRM6h8SZxmTIdJGBOcrN1m9YNJTk7ZEsa6HsfeUjGJuAb9XStJMHNlNU3hixmTYZqsqPp91V7Swv11WM4EVCowTJoP1l0Jo7WkTTKHC9MaJhrbJzjmFE1dHkK+qFagqWPCsFX8Su0KsXUWO/+Mm1swR59bNB1FW62V5GDVulktXaE5R6dTyCPFPMIgnhzJxoNgmwYJ8Stt0il4U=
