language: node_js
node_js: 4.5.0
cache:
  timeout: 600
  directories:
  - node_modules
  - jspm_packages
env:
  global:
  - secure: QePV3x32sUfjwzvi40qC8s83tTEq4jPnqDqUN0B2vOEQsIOei5te7+E7li/FyjI0YqG+WOhx31DvBM9GXLT2zoZySoeNv9ud1R0wH1Eplpl2hBHg8VkBgNJcJuMkHxujSKIKz9TDjT02sUw3aGKE4hdsUxJWNyEwtlXSt/c35BXHX+1e0N9JjKFSmCnNQbfHlQ8ag1HA72SGzYlCeXW2Tks+ywg5Jg15wtE7DX+TQeuajoHfydsu8VNFPWkplYIrv8wdXEXmSS1V40PYOScAJ2vQPexI0a2HC9+2kK2K73YwF32f2hO+bxtrhlzfOj6FSRId877EUMrCyy55SI/1jmBIDYpvSTHVDVu31qY0YNk4A10I9IokD1sROSnmm0lIOPDUPlz7VBAA7eVXK+tvGJlXEnb+2BJCXQsSvcw9rd2sQndTh2vrjfnK7j3wEorq/s9NqID9ZaiBjTbZBMpwqiICSd2jZUhA/qovke3ZlvlMIKZtMZs6Vqd/n7AzKIw7vra+dJafINZUj9+n/GVXwwmvb+Mz9H3xNv1ElZKv4rQx/jxkKnr7lMawRyFJFvQPaTQ1+Ad2gI+C0BAoPatYQnt42ioCUcRrAGteAh9V6mE8mxCCMQJtfxjUkCoW2M/W1HOQayM7VWbawK4P6X6pYpIWOF73AcMtqZ0tV2uRDZQ=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$TRAVIS_BRANCH
  - HEIMDALL_BRANCH=$TRAVIS_BRANCH
  - HEIMDALL_PACKAGE_NAME=heimdall-ui-dev-$HEIMDALL_BUILD_LABEL.zip
install:
- npm install -g gulp
- npm install -g jspm
- npm install -g coveralls
- npm install
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install -y
script:
- sed -i "s@{BUILD_LABEL}@$HEIMDALL_BUILD_LABEL@" stageConf.js
- sed -i "s@{BRANCH}@$HEIMDALL_BRANCH@" src/main.js
- gulp bundle
- npm prune --production
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: PyYp43OylKD6PU/yMtaVeCl5pl0eQxKHCKu4tP0SOl7Xq2Z0Bt6pcg4cfoHC0gTOoarFEPQMdSHDuLNqq5i2BG2QPD3kQkCNAXs0410dePgfx96AdjyeQMMtArqr32HJyjUod1xUrf8av190Fi6l2KRHVQSBK4kru2wwc6Fosw0cw4YHrT0VhmrgLaWlvbHyr3WyyRLhVwa5OGS05Y1KoeSMdrIamh6Np1618cKr7aCJ5EZJAgTqtJZKaEWfXZlyZCtj065DoVZete+BlxlGtdsWgj1n0MnDBBxImn9i4+cb/xl8stpL6WgM4VUO8V1jSR2ORG2X5yhGbcvkZlMmVNRsfpHoofSuhEtFUzHUxTvhFoZ/hA8/mMpEdK71Hyz8YXYFfLpYTIhJTP6sw+A80HATOPXcYuTg5UKt4XAw5w3969KG2NL3vxnv2b6tq61QxjH0ZCGb50lRM6uLbhicjT9LUQgdtRXXIPL+Gmfpjd2v8CFI7cZNhT1lCVe7usXUDLmAQkCUdBtuLLE+Krxi7LChYhA9+gwABxPzX7hcyTl6WQfCMH1lzLlmR6WS+c/qgOtPLaHha/Bmf2NFmY561x9LFpH8Enx8mupodqTTiaf+C6pDeKcv0d1CnK6y6fWCtuLT/pRrSkOXBssdvts0NUBDbIpzDUl6VqKA50KK5Ps=
  secret_access_key: &2
    secure: a9TF7WF/PgWddUoaSPO83krtt3YCJvXY7XDNVG8i/Uj4wxmaW8YnsBmgwavHSkfEmPMhRzLao+rqTu/B5WKvLDqut22hLZmcthoz/q7X9i4eO1F+gPfMzXzs4Vg0CCaYOsj2muabV3/frOdI76hNhvLnEemhi+lonVwJMp3OtyNol2y/YFwnoIIJ8uvjkoZC9RJBOdDNDeS08RGZbn3vGCjt9C6JZ87HjGEd1/bafDVHmsBQWSG98bS1ZF/FKJdFrqgwOe+QpR2LFSjETTdWMIjwO3hJ/VBUxngyo3Y6JOe4uvFP9r6E/2rxkn6NNiuCi0QSRHiwSntu3MqTK97VrGqn2PtCUkO6e0OuZVsykRRx04AUPMZ77f0r32TGSKxHnvrm/H/YKentSuwdPiVMoTCrMDX9lRuvyK8L9+9TPKlAXd0KExazvoeRvapP9UCcU0l41u7OMeW9QwsCPcHqk7htn71mlqwFlYnCRz+TGQYQFEdvitEg6by3tgmB9oT5HTL3i6/DTE1eeUtIQiAHBk5p5e6jrcDeaSwfqXGlyEJwh0Yo7zVIeurnWeH/u3YTajJemEa+/FXXlX6Kz3i5nSxeITZzWuPurzavuIaI96u09FtY+d4Zqk7HkPiQIbPWpQ8AEVvmVq3fLVt9M1p6rZxPAhhKxNgqLC+4CdfoexI=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-uiapp
    branch: development
  bucket: dev-heimdall-ui-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: dev-heimdall-ui-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: dev-heimdall-ui-app
  deployment_group: dev-heimdall-ui-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
