sudo: required
language: node_js
node_js: 4.5.0
cache:
  timeout: 600
  directories:
  - node_modules
  - jspm_packages
env:
  global:
  - secure: WTNar2gucwqFKH/dy99vfPlSjK8x9VwETZIOfZ6qxF/tLqNmky0O5t8rDA++UaPVs/omxi8AceeZedhpNAU+/HUy8dwWGFS56xbjDf1x5VBwa865VIYlofp6pmCieyIs2snBuXUdNgflU18gSb+Tp19kuJOQwcrVgULiUNDD9JU4ZbOccreV1VNFJGZnDTe9eHjhWPRu1+Afjn1PlMlPiVW/l2tD0eRinSLzw5KcOY+5vOwlFcMCwRy6zFEq+QdozW5bTDukUol4ann7UdkhcRKZCFv82hciElnN5BDAaKxLcaCqskFbrOs7TbqebTOn1fb8fOPFwrrS41ljEIqfEA6/W3PeTTmeTlGqwgx34TcnAZ3E7yYX0BlLzgvtcI8aWnvhpjuINUfVgFi7TXhV2lfdq7uxy1USIDwyozNXxg4RiZHLXkCqy2pXWEH+YN7HMx3lD8kyLpyANydtr4vj105dYFVVN2u61K+IrhIFeagJ2oefbtRX2L+mIq0E0Cth4is7rWW9QF+9qM5XQ+3LY9Ah9e+txBSX9td1Z/o/I2v+kx0wHmmYzW4VvhPoUC3as19cbaZOqKI7gEZK9q1FCi/Xj9T6WfZL3SXKClBJThLH3l+sImRLZTYdQq9waDZdQAFbTAGl0z19x2XFKS6fHDYEsPsmgWpuIDR6QERZj8E=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BRANCH=$TRAVIS_BRANCH
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$HEIMDALL_BRANCH
  - HEIMDALL_PACKAGE_NAME=heimdall-ui-dev-$HEIMDALL_BUILD_LABEL.zip
install:
  - npm install -g gulp
  - npm install -g jspm
  - npm install -g coveralls
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install -y
script:
  - sed -i "s@{BUILD_LABEL}@$HEIMDALL_BUILD_LABEL@" stageConf.js
  - sed -i "s@{BRANCH}@$HEIMDALL_BRANCH@" src/main.js
  - gulp lint
  - gulp bundle
  - npm prune --production
before_deploy:
  - zip -rq $HEIMDALL_PACKAGE_NAME *
  - mkdir -p dpl_cd_upload
  - mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
  - provider: s3
    access_key_id: &1
      secure: eppFdNSgdITos2FjRjfsNXQtFVVb0ersV+eLK0ll4cZmlXgkckUQi0lDaAgNyp/seeOxCoIqdEs4hvmPeznognnG6McIGHnntShNbsk+c4jwuCxGb4OpoxshNQr6/3FEXmSLSe2XO93H2zrWxyxmHchuqXav2m/b6bDG2mIdhqK5Xs0OZTSbF2AGOguZBZopb0V5RV4IVZGzx1Kj7x1bN0m14JDGtcnGwN2KsxiK46UizeKjcbsUH1DeyZatUrCKx5jiVcXHj6LP1ydxXYeG5asELf8uORdhMbLTou/k743qDeruFNzYWproJiCxyhao9f7Ktpu+2EPKt1lasoDgr4qzp8Fr5r3+lx9HS7KZmKNUVmTNyHc6+DG5ErjKg+zePgP7iaA02cPmxn7p7UEes6O17kDfrogSvDrhINfJ1bIeUmeOuhZ9do92FE70i3y/Laek/n9CfxI0KVp2dqGSPQRqohn8MCXk2YaKJF1/n/aO6QvcA9Y3rPtuzYDzTHAOrBTMS+7u7ZMe7ViQATPOQs16vR9mDts0759LNYDnLcFLmsv9Ekb1PRy9Gzde1bAoP02khfeN8GcdwhnDS5OePhRCrkrN3a5GDi2m/F6dC8GOvOvr+Mmj1TitvR+F24tnMEeBlqsvpV0gsVIDIQK7aOYazlkR9z3xgB83kd2yR+c=
    secret_access_key: &2
      secure: szRS6akDk/QF+Q9ScLBILeAYqffuNq1FqUUtF+/pRkSlP8h67BzelwCsKoytCipA+FGE+eSmq6Bjvxs7F86qgbjeSyMo3WW/qcQEHRrQKyrUhbKekIZWGCmJBewM/GxxKMHc/55q5hKmvxIBkM7Q6ByDE5IZE1OP2otnjj8pbYlvpYOo3g7g1LlMKQ3f4WB44ieREqjiBIKuP0E6e3t5/Zbz90pSWPTpTvAGiLwpTQiLDZOhXGQdlqndg5VFSUQ6g1miTb8xcF5itPdpMxn2tG1pmD6QfBwEa1Q78W9XMMYTzoKtX4y2UD+wTfwO8MSP51vw18iIjV9/654//VzS+jc1GHD8U+13Cpjr5tY/v09uNZKtOjM7BdCVy8/pudRAlsqK9tqFUIo8jOf0UYpqlGQwJDWaS+qD/dSLGyNeggeA2i7I4UrCcJnX6cSL6ycYtuq5iNGHJEwdXEmyIHStH4DPE89i9m169CSzI0+01sQje7UQYi5W75Pa2c17nyDeBhbLXyJ6Q6YGQ9Ul9XS1BJvpfoAqeBsSMRxjkCMVTXOWhKPP0XQ5QVrxP6TeIH1x3tivk2r0Vi5xC5QW29C0Y2ydwUcvV84bJRu+7unmLinVHHAAymvMn9Hnl8RMdzOQIGOI8y4cVp8pq/a6L31mxe5+IlD6ZwzzCIVt/xpazis=
    local_dir: dpl_cd_upload
    on: &3
      repo: Project-Heimdall/heimdall-uiapp
      branch: development
    bucket: dev-stage-ui-codedeploy
    region: us-west-2
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: *1
    secret_access_key: *2
    bucket: dev-stage-ui-codedeploy
    key: $HEIMDALL_PACKAGE_NAME
    bundle_type: zip
    application: dev-stage-ui-app
    deployment_group: dev-stage-ui-group
    region: us-east-1
    on: *3
    skip_cleanup: true
notifications:
  slack:
    secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
