language: node_js
node_js: 4.4.3
cache:
  directories: node_modules
env:
  global:
  - secure: Ch1QMswEx5wTrgn/TwEFjbMd7p2di9p7NgGTff43EcambfqZeP+NqQQ+RI+fnSXeJWLxrUopSVXZi+CIJEtey4B92lo6J+HetspzVvLygcdenpFzrB4PYiA6YQXj1V/MFzDHZQ75WbgaqWLeuQjR+XteTnWqI8Nd47xbehRELCn4LHsCX82+Ay3s1Ygc0pgwWv526yfmUt4oPj+dPv62KpHkL0tgBm/rcPQgKfJr3P+m5HkL7Mxl4j063KNOe1VksUgZCgdBe9QiVzKrUjPv7zCD2FKHQ/htsjAMATIi8fikL2din8KwAjRCeZ1H1cZMtANeAPyngUQoSrjUi40rUCe49cam2YddYxL00QcelizjR6gR6I9v2J+9jUVHumSbYR8/Z5ol+r3rNOB0IrfMIwdYVgWVRS1LqLMAw0GiUwqin1fi///lmH83LldIPLtT/AODi4Y2virO3+s5JmCJrxK3oQnHRFeEeH9ntUXcQ/YuHpjom2kjDuJifR6XOwPlT2Toap+EMBnagY0lyv/Lap+ENedjXzgVXbgSvINHpGCEyCIY6/2D1yOBnh37cPp7ChMcOtSdZQbqGgRvRlaoZ0xkFmeBSvBQybf5/awh+uaAa2plcXN+y8vAz47lwEjol67ewjNPa5l/cg04pB9WQ94LnNndZSpX1dkdwaJ7KGc=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_PACKAGE_NAME=heimdall-uiapp-$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$TRAVIS_NODE_VERSION.zip
install:
# - npm install -g gulp
# - npm install -g jspm
# - npm install -g coveralls
# - npm install
# - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
# - jspm install -y
script:
# - gulp build
# - npm prune --production
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
# deploy:
# - provider: s3
#   access_key_id: &1
#     secure: KRaLbFj2S733jLaLcyu6zACwFVE1z3S4ADHLFctUto4lg2cVLMh59j84F546z0V4fSf8tYyynX/wMluNDGuTlqb/p/i5ZbaFF0mI+d2RTSqpNNkfGTJgd+C3oet9dFUJMA0kEbBeNH99d69P1nHqIzlVDWZAhZqgIySCAvaT9CIDCRwAe8CywknYIuvGhtLC7tdgIiGy8uWYma5LuGARQZCdftSSy7mZmGWzTEsCWByvIjtEBLzUVO7dFivT002M4BozG8epfXJ8VTYnIy4SkLrNtz3QF6xfsFnve628dmNeq+eY0i41kY2bRyUxTiu73EVf4WhV9YEue/Ftm2QiHJ5qKnbs+G6AuKSmtYvb5Ch5xwjaQdN6AeaW6acTdy9yAaEkCIPk+/3un4idHGoUkzE1zbfC8RC5IsYE5JCZy8t5PdFW1VER4m4knfIi/PXjY4hGRGOL61nzwepP+FQ/WwiKvhOLifGqklj49Ujc+R2KspaN5yrf72riXiXrIePkEohsvIvRuGPgCRZzMkGL/NRFTkG2Ob6Z2gSUgbfEZZmrgPTJLnQpkGhl27jvUsL77n+kAis//9ZTdZ8fXeEb0cRRzv6cLRG3WmY+uHEeH3WQphK7V/WhSvRvZDOO9RDyOPclyNZ6L29dA+z71Jciha1388e+Kuo1/U0C6mjnvL8=
#   secret_access_key: &2
#     secure: PIEYDBX2Zh6Bh6amt4pJ/HtXFKQ/prQpOSGxKCYpm8sGaNbsdp8HTyX/x+lNUeSt131S+YPZFar/l9v73LbJ30ySvfCv7DV8HkozSjurhsYW0hR+f61JyANq98Od9bi3h3zG+UdDECrO0JnVvL6D5bYCrAEQM//AYrotrjbF6lzWSBvpUjTKCeSWK7qm2ykLyOfVVm5kCSVuaaLSZCF2q4avxPTgQzwAM3lyXtOCvdKA4ynEZQNnBve2cWSw9VT7pEqRXpt45S2e3y2NOa7dscx3WOfpTroZeX6kUXkcHSqC45ZI0uyM6FK+/5j+hXWkhPb9BhPKBiLSHKIRKHGAFrq5HNSHvC24EO+wPFzZ0tE07jyMNqRyL+bSxsfIdy7wbOqysTw7PvG8ialpZVsRisRjk5kelcQ+2GciIkNjlnoUniirhYKtGZyRqDXvpriHd1JYyvQr4BnZEti5XEfp0CmRANdVqQUiHdWBx0MSGF86vQGcBmh863DYEWS8AieB6Gxk9zKnHRMq21N52Q17v8rK+YovZ857Pbss42eyJTL0VNeRhjkXYHOTx/3OLyenoVL3y6nqnRkXmfdT/9fgOO9e23J1yBttxY+ZJ1W6ElBod8wnW3GWXhxDR+rUSR2PvgQseIVZbehoNa51v1Xrg86xP4/S60v/5KfIrxcrcmQ=
#   local_dir: dpl_cd_upload
#   on: &3
#     repo: Project-Heimdall/heimdall-uiapp
#     branch: master
#   bucket: codedeploy-heimdall-uiapp
#   region: us-west-2
#   skip_cleanup: true
# - provider: codedeploy
#   access_key_id: *1
#   secret_access_key: *2
#   bucket: codedeploy-heimdall-uiapp
#   key: heimdall-uiapp-1.0.0.zip
#   bundle_type: zip
#   application: CodeDeploy-Heimdall-UIApp
#   deployment_group: CodeDeploy-HeimdallWebapp-Group
#   region: us-east-1
#   on: *3
#   skip_cleanup: true
# notifications:
#   slack:
#     secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
