sudo: required
language: node_js
node_js: 4.5.0
services:
  - docker
cache:
  timeout: 600
  directories:
  - node_modules
  - jspm_packages
env:
  global:
  - secure: M3U6JYQhZeLHwu6JPjwGJvhre+2eDwrgniY0RfXFHAeIQXtaFXP226odkw6GOreYYxxmfDY3Fo7xljmdSZIGhqJ0ETr2jOh7/lz0tbQxrAeJBDJcwCQa9XdUuuEciiHlPD/ysfeDltq3Mo1elXFDDVDQmX8kxHZuCqwFKoYrZ/lhXI7JRk9EigcomDunnAmNFFcOycBFPnOmYHXLPpOsye6ilnGr6SNvT5O8l84pegHudytDpd7VRvcYr5677YmJbmPbK133yPYJY4kt95z51/EDiGh3J5zSB+7plcti3vGuVKTv8IgC+oAdNKoa25nV3NI6Ye+Kyu3ubSaTW2GLuO06x0uNeEcGmHK5DvtigBPM4DfKh5aC5VjWdNAXhRAE1L6+bmap7kBQqQH07Y04WpKg8eIh62XoyVhKEurXXhUW6j+cPVYYX4FXiGllnTcfUW1pcxgFrkjHwT2VX92hkL8vfC1fU2kfXg5CVaRMY0NMFh3/fAJKtgSPMcdEHYOVZfLz0u2/Yxc95p82cPHnrHbZq3W5TsTPDl3Lfh6wM0osfIkrj87bDaELjt+bIvzNqw1XKgePEW6+POO2GbCxS+B6exFtm4Xri4x7duK8OKJLyDhbRjSYIU/J4BHApaeVPrkjVYtRql173tUV0uTxUiyuiBSdYRssPmYIoQtRxsA=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BRANCH=$TRAVIS_BRANCH
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$HEIMDALL_BRANCH
  - HEIMDALL_PACKAGE_NAME=heimdall-ui-dev-$HEIMDALL_BUILD_LABEL.zip
install:
  - npm install -g gulp
  - npm install -g jspm
  - npm install -g coveralls
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install -y
  - docker build -t stage/uiapp:$STAGE_UIAPP_VERSION .
script:
  - sed -i "s@{BUILD_LABEL}@$HEIMDALL_BUILD_LABEL@" stageConf.js
  - sed -i "s@{BRANCH}@$HEIMDALL_BRANCH@" src/main.js
  - gulp lint
  - gulp bundle
  - npm prune --production
before_deploy:
  - zip -rq $HEIMDALL_PACKAGE_NAME *
  - mkdir -p dpl_cd_upload
  - mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
  - provider: s3
    access_key_id: &1
      secure: f5fveO3p5jRpGK5Q8CF04x5l1RmJwHN4K6zvO8XLFuDgzIktjZ9YhTW5amaI49VB6jq9iNXIrJPZ/D0yCKeTIikFjsXZ1Dkp27e16LR0L7WLkKmDedxSnQ7vxG7bqe9wsZCTKG5j5ZQ6ndPFlEAW5SPd3+n/4MJic/X+O62u8K91teNANfVyyBbjgLKq9mkaD7x6GanICoF6U9p2WhPLc5hrspIxqaUyNKwKrYlwWlInhk27ziwR/RQKtZj2tOirtMFAvJP5grGescEaMd2b2C+OZ7W0mXLdvxbRnvt3EJdwUmFz/Z/ptfDMwHdsL6pQCzuuQ5n4UKJ7vS/XIntjWw6yfq0w75ZbUaQlYrap2hBymgmEoE4P4q6ssMqyJUlreM3M4401so6agB/IF+8PL8fEKYEd1TBktzq5NMIvUGa9k1sATGTjUSKqae2w25P/f4XCeIEicH6vqnX8gHCj5wEwp8KBGgi61GAyzwCjqQZD3iyUCd2a6Bh4UzrlkC5XZDAugPu4I3Xmc+ZkQUPQmvdPYgV0rt9cMDiiLY5wJmDDRwHq4pCvQE+fnHky2bZLaKuXFKqK/mN5xn0e/qZsIu9kvPgFiEdqEe+ZMCGXRf8CFjTpw2QKsUkhUZoA6mLZJTn4PGC0Fkl+gfGl5tujtGEUUSA6gGhaSm6rM9005L0=
    secret_access_key: &2
      secure: URMo2xJi0MKl4gaC9bX2qzZV45NCVMcAVUDaTIGWOPNWIO2mFevbzeX1C5RzTB+J/lwEPc5SICzWkGZTtQtTJParcuzosQp1XNbC4+t+x8oAscqohicQ/5NtTl/B+qDAVtS94AhT+D9aNuw7lTFlyDhzGskP4TuTFNBO/7QZIos/3NWMprTiywbhG+D25+4Dhofc/r4J0NJ0gL3+UtCTUtbtIIdBLcLAJxNIeaVlNbvZgsffOledI4p6hQMq4sEJiNdNsJwrkMYIOSJTJ5eL/XhDGkOeLAnVa2lg/nUeZb0JMITIKNglHGktytf3zaxlfmxXSwyuSwXSX7/3xvhwhevLSLuex1piGuppGL6iYxduvKFv6yruEYpQZ/IcMiozxzEmDPw5LZ6iZaNAR40t0jlrawwXiivo0sw6xAKUL9r+JNo4qJ6fZMynjBY/9BQwKrJHIpaOgJt3JUbDVpMSdQhJmco16j+CnNM8AQKj35DrkMsLFZwSFDyX7+6viTDiHgDA0A47SBxiUCXrIM2AxVQyoUlb2Mmlvcx0974gdTTOFVKhiGHUjsNPM6uA6DSTC2kYj4ib4WZJ4OZyqjeb57hTNKgQT8S462PSrB93oNI5gcY4KnfghothP+wORnyup+BCGxRQK7Vav8lDl/KBUMMZU0AgKztEgxyBFCVB8mo=
    local_dir: dpl_cd_upload
    on: &3
      repo: Project-Heimdall/heimdall-uiapp
      branch: devops/use-aws-ecr
    bucket: dev-heimdall-ui-codedeploy
    region: us-west-2
    skip_cleanup: true
  - provider: codedeploy
    access_key_id: *1
    secret_access_key: *2
    bucket: dev-heimdall-ui-codedeploy
    key: $HEIMDALL_PACKAGE_NAME
    bundle_type: zip
    application: sandbox-heimdall-ui-app
    deployment_group: sandbox-heimdall-ui-group
    region: us-east-1
    on: *3
    skip_cleanup: true
notifications:
  slack:
    secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
