language: node_js
node_js: 4.5.0
cache:
  timeout: 600
  directories:
  - node_modules
  - jspm_packages
env:
  global:
  - secure: QePV3x32sUfjwzvi40qC8s83tTEq4jPnqDqUN0B2vOEQsIOei5te7+E7li/FyjI0YqG+WOhx31DvBM9GXLT2zoZySoeNv9ud1R0wH1Eplpl2hBHg8VkBgNJcJuMkHxujSKIKz9TDjT02sUw3aGKE4hdsUxJWNyEwtlXSt/c35BXHX+1e0N9JjKFSmCnNQbfHlQ8ag1HA72SGzYlCeXW2Tks+ywg5Jg15wtE7DX+TQeuajoHfydsu8VNFPWkplYIrv8wdXEXmSS1V40PYOScAJ2vQPexI0a2HC9+2kK2K73YwF32f2hO+bxtrhlzfOj6FSRId877EUMrCyy55SI/1jmBIDYpvSTHVDVu31qY0YNk4A10I9IokD1sROSnmm0lIOPDUPlz7VBAA7eVXK+tvGJlXEnb+2BJCXQsSvcw9rd2sQndTh2vrjfnK7j3wEorq/s9NqID9ZaiBjTbZBMpwqiICSd2jZUhA/qovke3ZlvlMIKZtMZs6Vqd/n7AzKIw7vra+dJafINZUj9+n/GVXwwmvb+Mz9H3xNv1ElZKv4rQx/jxkKnr7lMawRyFJFvQPaTQ1+Ad2gI+C0BAoPatYQnt42ioCUcRrAGteAh9V6mE8mxCCMQJtfxjUkCoW2M/W1HOQayM7VWbawK4P6X6pYpIWOF73AcMtqZ0tV2uRDZQ=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$TRAVIS_BRANCH
  - HEIMDALL_BRANCH=$TRAVIS_BRANCH
  - HEIMDALL_PACKAGE_NAME=heimdall-ui-prod-$HEIMDALL_BUILD_LABEL.zip
install:
- npm install -g gulp
- npm install -g jspm
- npm install -g coveralls
- npm install
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install -y
script:
- sed -i "s@{BUILD_LABEL}@$HEIMDALL_BUILD_LABEL@" stageConf.js
- sed -i "s@{BRANCH}@$HEIMDALL_BRANCH@" src/main.js
- gulp bundle
- npm prune --production
before_deploy:
- zip -rq $HEIMDALL_PACKAGE_NAME *
- mkdir -p dpl_cd_upload
- mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: aBwmxnCAV7An271TMQQT0i4NJXyezaU0Nyjo2Wfh5Byl/wPILpaeuhB3Ce0bIhz2KW6ujB5wBU4xRBTvQW0LqwQqiAoJ6PoYxJhgygnmhHil+osfmS7foXGmedvzdWVuNqFlCmbv7VhX56K7/kdHbz94Nag6TaRC6pgV0Z6JL3k/6n7jQrTh2V+DvALsHqYFTrSfk6ayhCazDfjPf8m+ia3Vysi/GsMi/xt6wcmaNBdHTJO+kZJhdFiTEMhhbAcLjrs5Y3AlImmh0dzKkdyrp7BWrrSE2XYGhL5cx/KI1MT5zgP2RCZbY0MCP0GhJAB0ngIJl2Rpg4qAEXlXrDjNdhfsHF+5XmV+OHp5tIWdKH1zTv8hqGT1fI9XhCyz/cef9dUFcj+j77yGABPTBB+XgEc3L7y99xjOyueb1QV94gF/eMqfdiagRhTt7OxLRt6CgUuaj8rN6sWR2P3dqv4eBjlGAn37GfJWkytjJb3PtZ7hnUHqVpZGmAH0KaSCurZ4fqxv7EyngbnQ0gXzYwe/QwlFzmYM9hXLqoPZ24TEiF1VEaSImZ1kx7oEED38nQRm5OPLJ2WTEUyQq6AB8UquA53LeryffyF1Ys56+vegz63WK3EihZvwpfYDz/RmOWbEZohVRhVXczMHM6r2R4LtWDTl5b7FkrSMAVyRO9F967o=
  secret_access_key: &2
    secure: XIcS3ufwKVj0lhl4UV5V3ankosFIJS1SjLqeRxwR//KDs6wV4tIOYQV3Ok2E+YJsXAVj4y6DQ2Qxoq3ef872XIMLmfwIQF5k0colHptH+M2odUh+SlKm3zC0wLPn3xE4udDTLolYhO3t3U2OWnoaqcZFIh9VQjgPavC+C2WOEMsJspEUqSAVjE9KIQvWhz59a5ey5kap74fVNdBoNU1ajLhj5H1v0KGoF6g8Y/leKaI2poSFGEnIeYMp7U7dWU5Nl1HJTItpfe6ZVW26Wl4lcvywmEmUq00kdOf/jR3P0rMkkeXhlLA2G7qZMWZZKmhkOakQsElgx4mnorrWOQXI5D5NVC9gmwC4NFTFp07g3LoCw2Xd6jIniA414SSv7GcNFUmlAA7j855x3xG74nMtNlx5xDfn//IFXpkiwNXxE86yZEQKk/2oyrVR9Pg1i7kVeRjR58Id06GUvwAp7TZPcTHkCjpeaTZcy4blsJ67jm+seeBf/hgHkc6ZfZ3A7+XbNAvRkyOkKhe7CgKV06+vgdGOepMoe0jr9rPP7BR9LocccMmk3DUet1m79l/yU6hMJEQUO8AGL+G+WMW4eLQ894Q8j/rSeDphp41o1n97QlX0bqMs6t9BjWwTRUewpZ4gPqc5sHLmPvbKVhO64J+9WTnF21QMWMlRnKMiWx4g+Ro=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-uiapp
    branch: master
  bucket: prod-heimdall-ui-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: prod-heimdall-ui-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: prod-heimdall-ui-app
  deployment_group: prod-heimdall-ui-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
