sudo: required
language: node_js
node_js: 4.5.0
cache:
  timeout: 600
  directories:
  - node_modules
  - jspm_packages
env:
  global:
  - secure: M3U6JYQhZeLHwu6JPjwGJvhre+2eDwrgniY0RfXFHAeIQXtaFXP226odkw6GOreYYxxmfDY3Fo7xljmdSZIGhqJ0ETr2jOh7/lz0tbQxrAeJBDJcwCQa9XdUuuEciiHlPD/ysfeDltq3Mo1elXFDDVDQmX8kxHZuCqwFKoYrZ/lhXI7JRk9EigcomDunnAmNFFcOycBFPnOmYHXLPpOsye6ilnGr6SNvT5O8l84pegHudytDpd7VRvcYr5677YmJbmPbK133yPYJY4kt95z51/EDiGh3J5zSB+7plcti3vGuVKTv8IgC+oAdNKoa25nV3NI6Ye+Kyu3ubSaTW2GLuO06x0uNeEcGmHK5DvtigBPM4DfKh5aC5VjWdNAXhRAE1L6+bmap7kBQqQH07Y04WpKg8eIh62XoyVhKEurXXhUW6j+cPVYYX4FXiGllnTcfUW1pcxgFrkjHwT2VX92hkL8vfC1fU2kfXg5CVaRMY0NMFh3/fAJKtgSPMcdEHYOVZfLz0u2/Yxc95p82cPHnrHbZq3W5TsTPDl3Lfh6wM0osfIkrj87bDaELjt+bIvzNqw1XKgePEW6+POO2GbCxS+B6exFtm4Xri4x7duK8OKJLyDhbRjSYIU/J4BHApaeVPrkjVYtRql173tUV0uTxUiyuiBSdYRssPmYIoQtRxsA=
  - HEIMDALL_VERSION_NUMBER=1.0.0
  - HEIMDALL_BRANCH=$TRAVIS_BRANCH
  - HEIMDALL_BUILD_LABEL=$HEIMDALL_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER-pre-alpha-$HEIMDALL_BRANCH
  - HEIMDALL_PACKAGE_NAME=heimdall-ui-prod-$HEIMDALL_BUILD_LABEL.zip
install:
  - npm install -g gulp
  - npm install -g jspm
  - npm install -g coveralls
  - npm install
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm install -y
script:
  - sed -i "s@{BUILD_LABEL}@$HEIMDALL_BUILD_LABEL@" stageConf.js
  - sed -i "s@{BRANCH}@$HEIMDALL_BRANCH@" src/main.js
  - gulp lint
  - gulp bundle
  - npm prune --production
before_deploy:
  - zip -rq $HEIMDALL_PACKAGE_NAME *
  - mkdir -p dpl_cd_upload
  - mv $HEIMDALL_PACKAGE_NAME dpl_cd_upload/$HEIMDALL_PACKAGE_NAME
deploy:
- provider: s3
  access_key_id: &1
    secure: UNjp09kRNU64BGid/WLBsObq0riTFDiCd8kY6NoSt5o8rfIvNG0EhGqi3/RV+r3rvxE6U+FWlJReE59SYuAXp5zy1B+xpmrUvrc1CY5AH+KmaDNkbf8ngHd5bZM8U99Yql8woXs/7XMmffcUnQ2Xv6xjwOjcrjzPNtx4FlXyqosGAqs5AlCwze6Mgz6E7cJPb0tAqM1DZxPRXx7lH2oouryuoqCaAHZyfveppvmpOOR3VmkQPXy885pnT3Kr2gHOrpatGPPHZ73meFaYZ1l9l+Armxl13UiotVSU7s1KWEMict7doZ0rxV+mDHEvp0BrRBw8+GmenuvODvYSslrfEJR+c9bjA72Na6vF0dAgzPFCds0A6/Y38DzZovamRGcFibSgYP+8I34F7N8ymNwfiWMKLE7j0JowYtj/Tduj5IvEJ/Qt52Ta3BNP/dks4igXEJWeym+vSEuI+bnDCqB4Da28ULJZc3+eLTFPf4p93Zsc3r7K0cF49Lh1p9bR+QvpnULSonrfQwREw0HwmJXNv+Irpvdi+HdPdgOPblsdinN1SMbF2vsUJ3vaKpZjVmWHQOepnprnkPqH8ztRpBwNnvcl32PT47QVXkEno6lhhKnZdCo4t9ggXHhb8RzUmjziH5a50wpwB47cRT4oA0NAMU+LntLjRfllmVFczWV0g7w=
  secret_access_key: &2
    secure: dWywxTxQqX1W2WU4c3XzhdFIWxvjUWNYovKCAMzoLu7E63q64NP0kFCkhbKLVjnvYeorgdM/KD4CgcK9W01wYDyNy74VIuuIpYldY8u5uPzrfT4ObFlZ7UPJ6biFE2YKD0xm0ISMyFsFmIo2hUBhF/sFqJh4Xp5G+5CvuBx/2Rl2S/vbUqI7IcGtf3wJ9Lmerob9ns0wA9fKs0GflBOY6TLA7cRIvlh+F5+O/1RWY98lEN8na8qtegIRlG8M/Vvu/zpThHzI96jdUceSKRHi1OHMUKVoNXhjM3qT51iEhAbIVzcJqMbjB3u9pDnBEed3PnVvk7KOFH/cXMyVMaWt2VfD3YEPs/n3qOfBF/iEVhBRGOWjgCjTh9Dncmgj0dGTnWrLtR5YxmYEtI3Le7pZ4fPnWmqlK4SJlTK4BBPDR7RqAgVMDI8KcQuvojMEsDkRQcXyghN1noyQ5/sHPLT0xQ0CuPQK4vOolexlXmkDvYWn2fsXAh2y/MMu14FnctITYIMiq3vpSPxAZRnLb+NKVh10cZ8Zju7d3VgH0uHyK+93VGJozmDBTfJ83gd5wiSjL2qwpZ0Vlqmv2qmTionYc58CJVJbMJpf476gm2cfWO+zq5jJzRt2oeRlaWdL8pd8fX/m0NmdtvcsHWlUniOdbO9N1z9lPzloAl4zN5v5q9k=
  local_dir: dpl_cd_upload
  on: &3
    repo: Project-Heimdall/heimdall-uiapp
    branch: master
  bucket: prod-heimdall-ui-codedeploy
  region: us-west-2
  skip_cleanup: true
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: prod-heimdall-ui-codedeploy
  key: $HEIMDALL_PACKAGE_NAME
  bundle_type: zip
  application: prod-heimdall-ui-app
  deployment_group: prod-heimdall-ui-group
  region: us-east-1
  on: *3
  skip_cleanup: true
notifications:
  slack:
    secure: ohVGL0X/we+oymPIh+UYef2pdvfqwAzMAVrmJ8+P4J+hojiGUmTQVLeh0gcLw+eDg4E+IfYG0IfJzlIvxZj68unm+kMjy7Oa52BwcJhVBGCExfEf9QljM0Iv0XC6j/Hj3F6Qd7yywv18HEYhBi32f8tQRwRbfgc+aqWg/N1w8QuPWRnaEvsw+dLd0xCkBZ14fUl9A2jh2ey+LMf0KDBVi+2cltykruOTMaRdxHrSiW85gSEBzI68ihAZZBT+/YayXuFPRPFXaqxlfiLJN9Jo3RYcpq4gMFxRv/8Yxuxt5SANcqz+aDBjCioEiRxitwTYiMxLaIvvdunT5VUN+YZbkD/bHaF3dcqTN0EHmBC4CW+RHXeps6aQVfyrU1F/P+2DD1hAZGibTcQ3uC3gBYYOJj6MNGYTAqlscjvDiXzb5ZAd9rOdi0dqCkHFmZOXBJEe5U7LgGTUIh4ab9lt0LDbX1v25ExJA9p7CSgjBZtfEatGpctXS2IVJ2bwhUbui3C7aactlB7fEi0O3+RIRU15NHfTdiqXUOZf5w9x7zYyXaWnqjfu/LkGvlnlGkktcqlh17rPQQ/69NfAP3HZiU/tbcIhLF/5ItkZQm7logtWGbf05f7D/o/pJ9ZPyd1JPln4buQpKWg+574okEHbXEfKphNQt6/HYxbeROPGhoThy+o=
